trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals ubuntu-ec2-agent

variables:
  dockerRegistryServiceConnection: 'omarrouby'
  imageName: 'omarrouby/spring-app'

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'Other'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'omarrouby'
    repository: '$(imageName)'
    dockerfile: 'spring-boot-app/spring-boot-app/Dockerfile'
    tags: |
      latest
    buildContext: 'spring-boot-app/spring-boot-app'

- task: Kubernetes@1
  displayName: 'Deploy to Minikube'
  inputs:
    connectionType: 'None'
    namespace: 'default'
    useConfigFile: true
    configFile: '$(System.DefaultWorkingDirectory)/kubernetes/deployment.yaml'
    arguments: ''
