trigger:
  branches:
    include:
      - main  # or your desired branch

pool:
  name: 'Default'  # Replace 'Default' with your actual pool if needed
  demands:
    - agent.name -equals ubuntu-ec2-agent  # Corrected demand format

steps:
# Step 1: Check out the code from the repository
- checkout: self

# Step 2: Build the Docker image using the Dockerfile
- task: Docker@2
  inputs:
    containerRegistry: 'omarrouby'  # DockerHub username
    repository: 'spring-app'        # DockerHub repository name
    command: 'buildAndPush'
    Dockerfile: 'spring-boot-app/Dockerfile'
    tags: 'latest'

# Step 3: Apply Kubernetes deployment
- script: |
    kubectl apply -f kubernetes/deployment.yaml
    kubectl apply -f kubernetes/ingress.yaml
  displayName: 'Deploy to Minikube'

# Step 4: Verify the Deployment
- script: |
    kubectl get pods
    kubectl get ingress
  displayName: 'Verify Deployment'
