trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals ubuntu-ec2-agent

variables:
  dockerRegistryServiceConnection: 'dockerhub'
  imageName: 'omarrouby/spring-app'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'dockerhub'
    repository: '$(imageName)'
    dockerfile: 'spring-boot-app/spring-boot-app/Dockerfile'
    tags: |
      latest
    buildContext: 'spring-boot-app'
    
- task: Kubernetes@1
  displayName: 'Deploy to Minikube'
  inputs:
    connectionType: 'None'
    namespace: 'default'
    command: 'apply'
    useConfigFile: true
    configFile: '$(System.DefaultWorkingDirectory)/kubernetes/deployment.yaml'
    arguments: ''
